version: '3'
services:
  postgis:
    container_name: 'postgis'
    build: ./postgis
    volumes:
      - geodata-volume:/var/lib/postgresql/data
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gis
      # Is there no dad at shinesolutions.com?
      - POSTGRES_USER=renderer-user
    networks:
      - devops
  renderer:
    container_name: 'rendereurpoulet'
    build: ./renderer
    volumes:
      - ./renderer/map_data:/map_data
      - ./renderer/scripts:/scripts
      - ./renderer/scripts:/shapes
      # instead of deprecated 'volumes_from' directive with read-only option
      - geodata-volume:/var/lib/postgresql/data
#     volumes_from:
#       - postgis:ro
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - postgis
    networks:
      - devops
  web:
    image: nginx:1.11-alpine
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - "8888:80"
    networks:
      - devops

networks:
  devops:
    # name: 'reseau-devops'
    driver: bridge
#     external: true 
#     ipam:
#       config:
#         - subnet: 192.168.160.0/24
#         - gateway: 192.168.160.1
#         # - gateway: 172.16.1.1
# - 
# + NAMED VOLUMES 
# - 
volumes:
     geodata-volume:
